---
services:
  postgres:
    image:
      postgres:16
    environment:
      - POSTGRES_DB=task_tracker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  migrations:
    build:
      context: .
      dockerfile: common/Dockerfile
    environment:
      - DATABASE_NAME=task_tracker
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=qwerty
      - DATABASE_HOST=postgres
    depends_on: { postgres: { condition: service_healthy } }

  tasks:
    build:
      context: .
      dockerfile: services/tasks/Dockerfile
    environment:
      - DB_NAME=task_tracker
      - DB_HOST=postgres
      - AMQP_URL=amqp://guest:guest@rabbitmq/
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  rabbitmq:
    ports:
      - 15672:15672
      - 5672:5672
    image:
      rabbitmq:3-management
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics -q ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq/
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      tasks:
        condition: service_started

volumes:
  pgdata:


